version: '3'
services:
  app:
    build: .
    image: omardoma/bidblab-backend:v1
    ports:
      - "3200:3200"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - webnet
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
      - /root/database:/root/database
    networks:
      - webnet

networks:
  webnet: