version: '3'
services:
  app:
    image: omardoma/bidblab-backend:v1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - webnet
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: